package com.tomitive.avia.model

val notamCodes = mapOf(
    "A/A" to "Air-to-air",
    "A/G" to "Air-to-ground",
    "AAD" to "Assigned altitude deviation",
    "AAIM" to "Aircraft autonomous integrity monitoring",
    "AAL" to "Above aerodrome level",
    "ABI" to "Advance boundry infromation",
    "ABM" to "Abeam",
    "ABN" to "Aerodrome beacon",
    "ABT" to "About",
    "ABV" to "Above",
    "AC" to "Altocummulus",
    "ACCID" to "Aircraft accident",
    "ACFT" to "Aircraft",
    "ACK" to "Acknowledge",
    "ACL" to "Altimeter check location",
    "ACN" to "Aircraft classification number",
    "ACP" to "Acceptance",
    "ACPT" to "Accepted",
    "ACT" to "Active",
    "AD" to "Aerodrome",
    "ADA" to "Advisory area",
    "ADC" to "Aerodrome chart",
    "ADDN" to "Additional",
    "ADJ" to "Adjacent",
    "ADO" to "Aerodrome office",
    "ADR" to "Advisory route",
    "ADS" to "Address",
    "ADSU" to "Automatic dependent surveillance unit",
    "ADVS" to "Advisory service",
    "ADZ" to "Advise",
    "AES" to "Aircraft earth station",
    "AFIL" to "Flight plan filed in the air",
    "AFIS" to "Aerodrome flight information service",
    "AFM" to "Affirmative",
    "AFS" to "Aeronautical fixed service",
    "AFT" to "After",
    "AGA" to "Aeorodromes",
    "AGL" to "Above ground level",
    "AGN" to "Again",
    "AIC" to "Aeronautical information circular",
    "AIDC" to "Air traffic services interfacility data communications",
    "AIP" to "Aeronautical information publication",
    "AIRAC" to "Aeronautical information regulation and control",
    "AIS" to "Aeronautical information services",
    "ALA" to "Alighting area",
    "ALR" to "Alerting",
    "ALRS" to "Alerting service",
    "ALS" to "Approach lighting system",
    "ALT" to "Altitude",
    "ALTN" to "Alternating",
    "AMA" to "Area minimum altitude",
    "AMD" to "Amended",
    "AMDT" to "Amendment",
    "AMS" to "Aeronautical mobile service",
    "AMSL" to "Above mean sea level",
    "AMSS" to "Aeronautical mobile satellite service",
    "ANC" to "Aeronautical chart",
    "ANCS" to "Aeronautical navigation chart",
    "ANS" to "Answer",
    "AOC" to "Aeronautical obstacle chart",
    "AP" to "Airport",
    "APCH" to "Approach",
    "APDC" to "Aircraft parking",
    "APN" to "Apron",
    "APP" to "Approach control office",
    "APR" to "April",
    "APRX" to "Approximately",
    "APSG" to "After passing",
    "APV" to "Approved",
    "ARC" to "Area chart",
    "ARNG" to "Arrange",
    "ARO" to "Air traffic services reporting office",
    "ARP" to "Aerodrome reference point",
    "ARQ" to "Automatic error correction",
    "ARR" to "Arrival",
    "ARS" to "Special air-report",
    "ARST" to "Arresting aircraft",
    "AS" to "Altostratus",
    "ASC" to "Ascending to",
    "ASDA" to "Accelerate-stop distance available",
    "ASE" to "Altimetry system error",
    "ASHTAM" to "Change in activity of a volcano",
    "ASPH" to "Asphalt",
    "ATA" to "Actual time of arrival",
    "ATC" to "Air traffic control",
    "ATCSMAC" to "Air traffic control surveillance minimum altitude chart",
    "ATD" to "Actual time of departure",
    "ATFM" to "Air traffic flow management",
    "ATIS" to "Automatic terminal information service",
    "ATM" to "Air traffic management",
    "ATN" to "Aeronautical telecommunication network",
    "ATP" to "At",
    "ATS" to "Air traffic services",
    "ATTN" to "Attention",
    "ATZ" to "Aerodrome traffic zone",
    "AUG" to "August",
    "AUTH" to "Authorized",
    "AUW" to "All up weight",
    "AUX" to "Auxiliary",
    "AVBL" to "Available",
    "AVG" to "Average",
    "AVGAS" to "Aviation gasoline",
    "AWTA" to "Advise at what time able",
    "AWY" to "Airway",
    "AZM" to "Azimuth",
    "BA" to "Braking action",
    "BARO-VNAV" to "Barometric vertical navigation",
    "BASE" to "Cloud base",
    "BCFG" to "Fog patches",
    "BCN" to "Beacon",
    "BCST" to "Broadcast",
    "BDRY" to "Boundary",
    "BECMG" to "Becoming",
    "BFR" to "Before",
    "BKN" to "Broken",
    "BLDG" to "Building",
    "BLDU" to "Blowing dust",
    "BLO" to "Below clouds",
    "BLSA" to "Blowing sand",
    "BLSN" to "Blowing snow",
    "BLW" to "Below",
    "BOMB" to "Bombing",
    "BR" to "Mist",
    "BRF" to "Short approach",
    "BRG" to "Bearing",
    "BRKG" to "Braking",
    "BS" to "Commercial broadcasting station",
    "BTL" to "Between layers",
    "BTN" to "Between",
    "CAT" to "Category",
    "CB" to "Cumulonimbus",
    "CC" to "Cirrocumulus",
    "CD" to "Candela",
    "CDN" to "Coordination",
    "CEZ" to "Cruise",
    "CF" to "Change frequency to",
    "CGL" to "Circling guidance lights",
    "CH" to "Channel",
    "CHG" to "Modification",
    "CI" to "Cirrus",
    "CIT" to "Near large towns",
    "CIV" to "Civil",
    "CK" to "Check",
    "CL" to "Centre line",
    "CLA" to "Clear type of ice formation",
    "CLBR" to "Calibration",
    "CLD" to "Cloud",
    "CLG" to "Calling",
    "CLIMB-OUT" to "Climb-out area",
    "CLR" to "Cleared",
    "CLRD" to "Runway(s) cleared",
    "CLSD" to "Closed",
    "CM" to "Centimetre",
    "CMB" to "Climb",
    "CMPL" to "Completed",
    "CNL" to "Cancelled",
    "CNL" to "Flight plan cancellation",
    "CNS" to "Communications, navigations and surveillance",
    "COM" to "Communications",
    "COND" to "Condition",
    "CONS" to "Concrete",
    "CONS" to "Continuous",
    "CONST" to "Construction",
    "CONT" to "Continued",
    "COOR" to "Coordination",
    "COORD" to "Coordinates",
    "COP" to "Change-over-point",
    "COR" to "Correction",
    "COT" to "At the coast",
    "COV" to "Covered",
    "CPDLC" to "Controller-pilot data link communications",
    "CPL" to "Current flight plan",
    "CRC" to "Cyclic redundancy check",
    "CS" to "Call sign/Cirrostratus",
    "CTA" to "Control Area",
    "CTAM" to "Climb to and maintain",
    "CTC" to "Contact",
    "CTL" to "Control",
    "CTN" to "Cauction",
    "CTR" to "Control zone",
    "CU" to "Cumulus",
    "CUF" to "Cumuliform",
    "CUST" to "Customs",
    "CVR" to "Cockpit voice recorder",
    "CW" to "Continuous wave",
    "CWY" to "Clearway",
    "D-VOLMET" to "Data link VOLMET",
    "DA" to "Decision altitude",
    "DCD" to "Double channel duplex",
    "DCKG" to "Docking",
    "DCP" to "Datum crossing point",
    "DCPC" to "Ditect controller-pilot communications",
    "DCS" to "Double channel simplex",
    "DCT" to "Direct",
    "DE" to "From",
    "DEC" to "December",
    "DEG" to "Degrees",
    "DEP" to "Departure",
    "DES" to "Descending to",
    "DEST" to "Destination",
    "DETRESFA" to "Distress phase",
    "DEV" to "Deviating",
    "DFDR" to "Digital flight data recorder",
    "DFTI" to "Distance from touchdown indicator",
    "DH" to "Decision height",
    "DIF" to "Diffuse",
    "DIST" to "Distance",
    "DIV" to "Diverting",
    "DLA" to "Delayed",
    "DLIC" to "Data link initiation capability",
    "DLY" to "Daily",
    "DME" to "Distance measuring equipment",
    "DNG" to "Danger",
    "DOM" to "Domestic",
    "DP" to "Dew point temperature",
    "DPT" to "Depth",
    "DR" to "Dead reckoning",
    "DRDU" to "Low drifting dust",
    "DRG" to "During",
    "DRSA" to "Low drifting sand",
    "DRSN" to "Low drifting snow",
    "DS" to "Duststrom",
    "DSB" to "Double sideband",
    "DTAM" to "Descend and maintain",
    "DTG" to "Date-time group",
    "DTHR" to "Displaced runway threshold",
    "DTRT" to "Deteriorating",
    "DTW" to "Dual tandem wheels",
    "DU" to "Dust",
    "DUC" to "Dense upper cloud",
    "DUPE" to "Duplicate message",
    "DUR" to "Duration",
    "DVOR" to "Doppler VOR",
    "DW" to "Dual wheels",
    "DZ" to "Drizzle",
    "E" to "East",
    "EAT" to "Expected aproach time",
    "EB" to "Eastbound",
    "EEE" to "Error",
    "EET" to "Estimated elapsed time",
    "EFC" to "Expect further clearance",
    "EHF" to "Extremely high frequency (30 000 MHz+)",
    "ELBA" to "Emergency location beacon - aircraft",
    "ELEV" to "Elevation",
    "ELR" to "Extra long range",
    "ELT" to "Emergency location transmitter",
    "EM" to "Emission",
    "EMBD" to "Cummulonimbus embedded in a layer",
    "EMERG" to "Emergency",
    "END" to "End",
    "ENE" to "East-north-east",
    "ENG" to "Engine",
    "ENR" to "En route",
    "ENRC" to "Enroute chart",
    "EOBT" to "Estimated off-block time",
    "EQPT" to "Equipment",
    "ER" to "Here",
    "ESE" to "East-south-east",
    "EST" to "Estimated",
    "ETA" to "Estimated time of arrival",
    "ETD" to "Estimated time of departure",
    "ETO" to "Estimated time over significant point",
    "EV" to "Every",
    "EXC" to "Except",
    "EXER" to "Exercises",
    "EXP" to "Expected",
    "EXTD" to "Extending",
    "F" to "Fixed",
    "FAC" to "Facilities",
    "FAF" to "Final approach fix",
    "FAL" to "Facilitation of internal air transport",
    "FAP" to "Final approach point",
    "FATO" to "Final approach and take-off area",
    "FBL" to "Light",
    "FC" to "Funnel cloud",
    "FCST" to "Forecast",
    "FCT" to "Friction coefficient",
    "FDPS" to "Flight data processing system",
    "FEB" to "February",
    "FEW" to "Few",
    "FG" to "Fog",
    "FIC" to "Flight information centre",
    "FIR" to "Flight information region",
    "FIS" to "Flight information service",
    "FISA" to "Automated flight information service",
    "FL" to "Flight level",
    "FLD" to "Field",
    "FLG" to "Flashing",
    "FLR" to "Flares",
    "FLT" to "Flight",
    "FLTCK" to "Flight check",
    "FLUC" to "Fluctuated",
    "FLW" to "Following",
    "FM" to "From",
    "FMS" to "Flight management system",
    "FMU" to "Flow management unit",
    "FNA" to "Final approach",
    "FPAP" to "Flight path alignment point",
    "FPL" to "Filed flight plan",
    "FPM" to "Feet per minute",
    "FPR" to "Flight plan route",
    "FR" to "Fuel remaining",
    "FREQ" to "Frequency",
    "FRI" to "Friday",
    "FRNG" to "Firing",
    "FRONT" to "Front",
    "FRQ" to "Frequent",
    "FSL" to "Full stop landing",
    "FSS" to "Flight service station",
    "FST" to "First",
    "FT" to "Feet",
    "FU" to "Smoke",
    "FZ" to "Freezing",
    "FZDZ" to "Freezing drizzle",
    "FZFG" to "Freezing fog",
    "FZRA" to "Freezing rain",
    "G" to "Green",
    "G/A" to "Ground-to-air",
    "G/A/G" to "Ground-to-air and air-to-ground",
    "GA" to "Go ahead",
    "GAMET" to "Area forecast for low-level flights",
    "GARP" to "GBAS azimuth reference point",
    "GCA" to "Ground controller approach system",
    "GEN" to "General",
    "GEO" to "Geographic",
    "GES" to "Ground earth station",
    "GLD" to "Glider",
    "GND" to "Ground",
    "GNDCK" to "Ground check",
    "GP" to "Glide path",
    "GR" to "Hail",
    "GRASS" to "Grass landing area",
    "GRVL" to "Gravel",
    "GS" to "Ground speed",
    "GUND" to "Geoid undulation",
    "H24" to "Continuous day and night service",
    "H" to "High pressure area",
    "HAPI" to "Helicpoter approach path indicator",
    "HBN" to "Hazard beacon",
    "HDF" to "High frequency direction-finding station",
    "HDG" to "Heading",
    "HEL" to "Helicopter",
    "HF" to "High frequency (3 000 to 30 0000 kHz)",
    "HGT" to "Height",
    "HJ" to "Sunrise to sunset",
    "HLDG" to "Holding",
    "HN" to "Sunset to sunrise",
    "HO" to "Service available to meet operational requirements",
    "HOL" to "Holiday",
    "HOSP" to "Hospital aircraft",
    "HPA" to "Hectopascal",
    "HR" to "Hours",
    "HS" to "Service available during hours of scheduled operations",
    "HURCN" to "Hurricane",
    "HVDF" to "High  and  very  high  frequency  direction-finding  stations",
    "HVDU" to "Heavy dust",
    "HVY" to "Heavy",
    "HVYRA" to "Heavy rain",
    "HVYSN" to "Heavy snow",
    "HX" to "No specific working hours",
    "HYR" to "Higher",
    "HZ" to "Haze",
    "IAF" to "Initial approach fix",
    "IAO" to "In and out of clouds",
    "IAP" to "Instrument approach procedure",
    "IAR" to "Intersection of air routes",
    "IAS" to "Indicated airspeed",
    "IBN" to "Identification beacon",
    "IC" to "Ice crystals",
    "ICE" to "Icing",
    "ID" to "Identifier",
    "IDENT" to "Identification",
    "IF" to "Intermediate approach fix",
    "IFF" to "Identification friend/foe",
    "IFR" to "Instrument flight rules",
    "IGA" to "International general aviation",
    "ILS" to "Instrument landing system",
    "IM" to "Inner marker",
    "IMC" to "Instrument meteorological conditions",
    "IMG" to "Immigration",
    "IMPR" to "Improving",
    "IMT" to "Immediately",
    "INA" to "Initial approach",
    "INBD" to "Inbound",
    "INC" to "In cloud",
    "INCERFA" to "Uncertainty phase",
    "INFO" to "Information",
    "INOP" to "Inoperative",
    "INP" to "If not possible",
    "INPR" to "In progress",
    "INS" to "Inertial navigation system",
    "INSTL" to "Installed",
    "INSTR" to "Instrument",
    "INT" to "Intersection",
    "INTL" to "International",
    "INTRG" to "Interrogator",
    "INTRP" to "Interrupted",
    "INTSF" to "Intensifying",
    "INTST" to "Intensify",
    "IR" to "Ice on runway",
    "ISA" to "International standard atmosphere",
    "ISB" to "Independent sideband",
    "ISOL" to "Isolated",
    "JAN" to "January",
    "JTST" to "Jet stream",
    "JUL" to "July",
    "JUN" to "June",
    "KG" to "Kilograms",
    "KHZ" to "Kilohertz",
    "KM" to "Kilometeres",
    "KMH" to "Kilometeres per hour",
    "KPA" to "Kilopascal",
    "KT" to "Knots",
    "KW" to "Kilowatts",
    "L" to "Low pressure area",
    "LAM" to "Logical acknowledgment",
    "LAN" to "Inland",
    "LAT" to "Latitude",
    "LDA" to "Landing distance available",
    "LDAH" to "Landing distance available for helicopter",
    "LDG" to "Landing",
    "LDI" to "Landing direction indicator",
    "LEN" to "Length",
    "LF" to "Low frequency (30 to 300 kHz)",
    "LGT" to "Lighting",
    "LGTD" to "Lighted",
    "LIH" to "Light intensity high",
    "LIL" to "Light intensity low",
    "LIM" to "Light intensity medium",
    "LLZ" to "Localizer",
    "LM" to "Locator middle",
    "LMT" to "Local mean time",
    "LNG" to "Long",
    "LO" to "Locator outer",
    "LOC" to "Locally",
    "LONG" to "Longitude",
    "LR" to "Last message received by me was",
    "LRG" to "Long range",
    "LS" to "Last message sent by me was",
    "LTD" to "Limited",
    "LTP" to "Landing threshold point",
    "LTT" to "Landline teletypewriter",
    "LV" to "Wind light and variable",
    "LVE" to "Leaving",
    "LVL" to "Level",
    "LYR" to "Layer",
    "MAG" to "Magnetic",
    "MAINT" to "Maintenance",
    "MAP" to "Aeronautical maps and charts",
    "MAPT" to "Missed approach point",
    "MAR" to "At sea/march",
    "MAS" to "Manual A1 simplex",
    "MAX" to "Maximum",
    "MAY" to "May",
    "MBST" to "Microburst",
    "MCA" to "Minimum crossing altitude",
    "MCW" to "Modulated continuous wave",
    "MDA" to "Minimum descent altitude",
    "MDF" to "Medium frequency direction-finding station",
    "MDH" to "Minimum descent height",
    "MEA" to "Minimum en-route altitude",
    "MEHT" to "Minimum eye height over threshold",
    "MET" to "Meteorological",
    "MF" to "Medium frequency (300 to 3 000 kHz)",
    "MHDF" to "Medium and high frequency direction-finding stations",
    "MHVDF" to "Medium, high and very high frequency direction-finding stations",
    "MHZ" to "Megahertz",
    "MID" to "Mid-point",
    "MIFG" to "Shallow fog",
    "MIL" to "Military",
    "MIN" to "Minutes",
    "MIS" to "Missing",
    "MKR" to "Marker radio beacon",
    "MLS" to "Microwave landing system",
    "MM" to "Middle marker",
    "MMA" to "Maximum authorized altitude",
    "MNM" to "Minimum",
    "MNPS" to "Minimum navigation performance specifications",
    "MNT" to "Monitoring",
    "MNTN" to "Maintain",
    "MOA" to "Military operating area",
    "MOC" to "Minimum obstacle clearance",
    "MOD" to "Moderate",
    "MON" to "Monday",
    "MOPS" to "Minimum operational performance standards",
    "MOTNE" to "Meteorological Operational Telecommunications Network Europe",
    "MOV" to "Moving",
    "MPS" to "Metres per second",
    "MRA" to "Minimum reception altitude",
    "MRG" to "Medium range",
    "MRP" to "ATS/MET reporting point",
    "MS" to "Minus",
    "MSA" to "Minimum sector altitude",
    "MSG" to "Message",
    "MSL" to "Mean sea level",
    "MSSR" to "Monopulse secondary surveillance radar",
    "MT" to "Mountain",
    "MTU" to "Metric units",
    "MTW" to "Mountain waves",
    "MVDF" to "Medium and very high frequency direction-finding stations",
    "MWO" to "Meteorological watch office",
    "MX" to "Mixed type of ice formation",
    "N" to "North",
    "NASC" to "National AIS system centre",
    "NAT" to "North Atlantic",
    "NAV" to "Navigation",
    "NB" to "Northbound",
    "NBFR" to "Not before",
    "NC" to "No change",
    "NCD" to "No cloud detected",
    "NDB" to "Non-directional radio beacon",
    "NDV" to "No directional variations available",
    "NE" to "North-east",
    "NEB" to "Noth-eastbound",
    "NEG" to "Negative",
    "NGT" to "Night",
    "NIL" to "None",
    "NM" to "Nautical miles",
    "NML" to "Normal",
    "NNE" to "North-north-east",
    "NNW" to "North-north-west",
    "NO" to "Negative",
    "NOF" to "International NOTAM office",
    "NOSIG" to "No significant change",
    "NOV" to "November",
    "NOZ" to "Normal operating zone",
    "NR" to "Number",
    "NRH" to "No reply heard",
    "NS" to "Nimbostratus",
    "NSC" to "Nil significant cloud",
    "NSW" to "Nil significant weather",
    "NTL" to "National",
    "NTZ" to "No transgression zone",
    "NW" to "North-west",
    "NWB" to "North-westbound",
    "NXT" to "Next",
    "O/R" to "On request",
    "OAC" to "Oceanic area control centre",
    "OAS" to "Obstacle assessment surface",
    "OBS" to "Observed",
    "OBSC" to "Obscured",
    "OBST" to "Obstacle",
    "OCA" to "Obstacle clearance altitude",
    "OCC" to "Occulting light",
    "OCH" to "Obstacle clearance height",
    "OCNL" to "Occasional",
    "OCS" to "Obstacle clearance surface",
    "OCT" to "October",
    "OFZ" to "Obstacle free zone",
    "OGN" to "Originate",
    "OHD" to "Overhead",
    "OK" to "It is correct",
    "OLDI" to "On-line data interchange",
    "OM" to "Outer marker",
    "OPA" to "Opaque, white type of ice formation",
    "OPC" to "Control indicated is operational control",
    "OPMET" to "Operational meteorological",
    "OPN" to "Opened",
    "OPR" to "Operate",
    "OPS" to "Operations",
    "ORD" to "Order",
    "OSV" to "Ocean station vessel",
    "OTLK" to "Outlook",
    "OTP" to "On top",
    "OTS" to "Organized track system",
    "OUBD" to "Outbound",
    "OVC" to "Overcast",
    "PA" to "Precision approach",
    "PALS" to "Precision approach lighting system",
    "PANS" to "Procedures for air navigation services",
    "PAPI" to "Precision approach path indicator",
    "PAR" to "Precision approach radar",
    "PARL" to "Parallel",
    "PAX" to "Passengers",
    "PCD" to "Proceeding",
    "PCL" to "Pilot-controlled lighting",
    "PCN" to "Pavement classification number",
    "PDC" to "Pre-departure clearance",
    "PDG" to "Procedure design gradient",
    "PER" to "Performance",
    "PERM" to "Permanent",
    "PIB" to "Pre-flight information bulletin",
    "PJE" to "Parachute jumping exercise",
    "PL" to "Ice pellets",
    "PLA" to "Practive low approach",
    "PLN" to "Flight plan",
    "PLVL" to "Present level",
    "PN" to "Prior notice required",
    "PNR" to "Point of no return",
    "PO" to "Dust/sand whirls",
    "POB" to "Person on board",
    "POSS" to "Possible",
    "PPI" to "Plan position indicator",
    "PPR" to "Prior permission required",
    "PPSN" to "Present position",
    "PRFG" to "Aerodrome partailly covered by fog",
    "PRI" to "Primary",
    "PRKG" to "Parking",
    "PROB" to "Probability",
    "PROC" to "Procedure",
    "PROV" to "Provisional",
    "PS" to "Plus",
    "PSG" to "Passing",
    "PSN" to "Position",
    "PSP" to "Pierced steel plank",
    "PSR" to "Primary surveillance radar",
    "PTN" to "Procedure turn",
    "PTS" to "Polar track structure",
    "PWR" to "Power",
    "QDM" to "Magnetic heading",
    "QDR" to "Magnetic bearing",
    "QFE" to "Atmospheric pressure at aeorodrome elevation",
    "QFU" to "Magnetic orientation of runway",
    "QTE" to "True bearing",
    "QUAD" to "Quadrant",
    "R" to "Red",
    "RA" to "Rain",
    "RAC" to "Rules of the air and air traffic services",
    "RAFC" to "Regional are forecast centre",
    "RAG" to "Runway arresting gear",
    "RAI" to "Runway alignment indicator",
    "RAIM" to "Receiver autonomous integrity monitoring",
    "RASC" to "Regional AIS System centre",
    "RASS" to "Remote altimeter setting source",
    "RB" to "Rescue boat",
    "RCA" to "Reach cruising altitude",
    "RCC" to "Rescue coordination centre",
    "RCF" to "Radiocommunication failure",
    "RCH" to "Reaching",
    "RCL" to "Runway centre line",
    "RCLL" to "Runway centre lights",
    "RCLR" to "Recleared",
    "RDH" to "Reference datum height",
    "RDL" to "Radial",
    "RDO" to "Radio",
    "REC" to "Receive",
    "REDL" to "Runway edge lights",
    "REDU" to "Recent dust",
    "REF" to "Reference to",
    "REG" to "Registration",
    "RENL" to "Runway end lights",
    "REP" to "Report",
    "REQ" to "Requesting",
    "RERA" to "Recent rain",
    "RERTE" to "Re-route",
    "RESA" to "Runway end safety area",
    "RESN" to "Recent snow",
    "RG" to "range of lights",
    "RHC" to "Right-hand circuit",
    "RIF" to "Reclearance in flight",
    "RITE" to "Right",
    "RL" to "Report leaving",
    "RLA" to "Relay to",
    "RLCE" to "Request level change en route",
    "RLLS" to "Runway lead-in lighting system",
    "RLNA" to "Request level not available",
    "RMAC" to "Radar minimum altitude chart",
    "RML" to "Remark",
    "RNAV" to "Area navigation",
    "RNG" to "Radio range",
    "RNP" to "Required navigation performance",
    "ROC" to "Rate of climb",
    "ROD" to "Rate of descent",
    "ROFOR" to "Route forecast",
    "RON" to "Receiving only",
    "RPI" to "Radar position indicator",
    "RPL" to "Repetitive flight plan",
    "RPLC" to "Replaced",
    "RPS" to "Radar position symbol",
    "RPT" to "Repeat",
    "RQ" to "Indication of a request",
    "RQMNTS" to "Requirements",
    "RQP" to "Request flight plan",
    "RQS" to "Request supplementary flight plan",
    "RR" to "Report reaching",
    "RSC" to "Rescue sub-centre",
    "RSCD" to "Runway surface condition",
    "RSP" to "Responder beacon",
    "RSR" to "En-route surveillance radar",
    "RTD" to "Delayed message",
    "RTE" to "Route",
    "RTF" to "Radiotelephone",
    "RTG" to "Radiotelegraph",
    "RTHL" to "Runway threshold lights",
    "RTN" to "Returning",
    "RTODAH" to "Rejected take-off distance available for helicopter",
    "RTS" to "Return to service",
    "RTT" to "Radioteletypewriter",
    "RTZL" to "Runwaytouchodwn zone lights",
    "RUT" to "Standard regional route transmitting frequencies",
    "RV" to "Rescue vessel",
    "RVR" to "Runway visual rangee",
    "RWY" to "Runway",
    "S" to "South",
    "SA" to "Sand",
    "SALS" to "Simple approach lighting system",
    "SAN" to "Sanitary",
    "SAP" to "As soon as possible",
    "SAR" to "Search and rescue",
    "SARPS" to "Standards and Recommended Practices (ICAO)",
    "SAT" to "Saturday",
    "SATCOM" to "Satellite communication",
    "SB" to "Southbound",
    "SBAS" to "Sattelite-based augmentation system",
    "SC" to "Stratocumulus",
    "SCT" to "Scattered",
    "SDBY" to "Stand by",
    "SE" to "Sout-east",
    "SEA" to "Sea",
    "SEB" to "Sout-eastbound",
    "SEC" to "Section/seconds",
    "SECT" to "Sector",
    "SELCAL" to "Selective calling system",
    "SEP" to "September",
    "SER" to "Service",
    "SEV" to "Severe",
    "SFC" to "Surface",
    "SG" to "Snow grains",
    "SGL" to "Signal",
    "SH" to "Shower",
    "SHF" to "Super high frequency (3 000 to 30 000 MHz)",
    "SID" to "Standard instrument departure",
    "SIF" to "Selective identification feature",
    "SIG" to "Significant",
    "SIMUL" to "Simultaneously",
    "SIWL" to "Single isolated wheel load",
    "SKC" to "Sky clear",
    "SKED" to "Scheduled",
    "SLP" to "Speed limiting point",
    "SLW" to "Slow",
    "SMC" to "Surface movement control",
    "SMR" to "Surface movement radar",
    "SN" to "Snow",
    "SNOCLO" to "Aerodrome closed due to snow",
    "SPL" to "Supplementary flight plan",
    "SPOC" to "SAR point of contact",
    "SPOT" to "Spot wind",
    "SQ" to "Squall",
    "SQL" to "Squall line",
    "SR" to "Sunrise",
    "SRA" to "Surveillance radar approach",
    "SRE" to "Surveillance radar element of precision approach radar system",
    "SRG" to "Short range",
    "SRR" to "Search and rescue region",
    "SRY" to "Secondary",
    "SS" to "Sandstorm/Sunset",
    "SSB" to "Single sideband",
    "SSE" to "Sout-south-east",
    "SSR" to "Secondary surveillance radar",
    "SST" to "Supersonic transport",
    "SSW" to "South-south-west",
    "ST" to "Stratus",
    "STA" to "Staight-in approach",
    "STAR" to "Standard instrument arrival",
    "STD" to "Standard",
    "STF" to "Stratiform",
    "STN" to "Station",
    "STNR" to "Stationary",
    "STOL" to "Short take-off and landing",
    "STS" to "Status",
    "STWL" to "Stopway lights",
    "SUBJ" to "Subject to",
    "SUN" to "Sunday",
    "SUP" to "Supplement",
    "SUPPS" to "Regional supplementary procedures",
    "SVC" to "Service message",
    "SVCBL" to "Serviceable",
    "SW" to "South-west",
    "SWB" to "South-westbound",
    "SWY" to "Stopway",
    "T" to "Temperature",
    "TA" to "Transition altitude",
    "TAIL" to "Tail wind",
    "TAR" to "Terminal area surveillance radar",
    "TAS" to "True airspeed",
    "TAX" to "Taxiing",
    "TC" to "Tropical cyclone",
    "TCAC" to "Tropical cyclone advisory centre",
    "TCU" to "Towering cumulus",
    "TDO" to "Tornado",
    "TDZ" to "Touchdown zone",
    "TECR" to "Technical reason",
    "TEL" to "Telephone",
    "TEMPO" to "Temporary",
    "TFC" to "Traffic",
    "TGL" to "Touch-and-go landing",
    "TGS" to "Taxiing guidance system",
    "THR" to "Threshold",
    "THRU" to "Through",
    "THU" to "Thursday",
    "TIL" to "Until",
    "TIP" to "Until past",
    "TKOF" to "Take-off",
    "TL" to "Till",
    "TLOF" to "Touchodown and lift-off area",
    "TMA" to "Terminal control area",
    "TN" to "Minimum temperature",
    "TNA" to "Turn altitude",
    "TNH" to "Turn height",
    "TO" to "To",
    "TOC" to "Top of climb",
    "TODA" to "Take-off distance available",
    "TODAH" to "Take-off distance available for helicopter",
    "TOP" to "Cloud top",
    "TORA" to "Take-off run available",
    "TP" to "Turning point",
    "TR" to "Track",
    "TRA" to "Temporary reserved airspace",
    "TRANS" to "Transmitter",
    "TREND" to "Trend forecast",
    "TRL" to "Transition level",
    "TROP" to "Tropopause",
    "TS" to "Thunderstorm",
    "TT" to "Teletypewriter",
    "TUE" to "Tuesday",
    "TURB" to "Turbulence",
    "TWY" to "Taxiway",
    "TWYL" to "Taxiway-link",
    "TXT" to "Text",
    "TYP" to "Type of aircraft",
    "TYPH" to "Typhoon",
    "U" to "Upward",
    "U/S" to "Unserviceable",
    "UAB" to "Until advised by",
    "UAC" to "Upper area control centre",
    "UAR" to "Upper air route",
    "UDF" to "Ultra high frequency direction-finding station",
    "UFN" to "Until further notice",
    "UHDT" to "Unable higher due traffic",
    "UHF" to "Ultra high frequency (300 to 3 000 MHz)",
    "UIC" to "Upper information centre",
    "UIR" to "Upper flight information region",
    "ULR" to "Ultra long range",
    "UNA" to "Unable",
    "UNAP" to "Unable to approve",
    "UNL" to "Unlimited",
    "UNREL" to "Unreliable",
    "UTA" to "Upper control area",
    "VA" to "Volcanic ash",
    "VAAC" to "Volcanic ash advisory centre",
    "VAL" to "In valleys",
    "VAN" to "Runway control van",
    "VAR" to "Magnetic variation/Visual-aural radio range",
    "VASIS" to "Visual approach slope indicator systems",
    "VC" to "Vicinity of the aerodrome",
    "VCY" to "Vicinity",
    "VDF" to "Very high frequency direction-finding station",
    "VER" to "Vertical",
    "VFR" to "Visual glight rules",
    "VHR" to "Very high frequency (30 to 300 MHz)",
    "VIS" to "Visibility",
    "VLF" to "Very low frequency (3 to 30 MHz)",
    "VLR" to "Very long range",
    "VMC" to "Visual meteorological conditions",
    "VRB" to "Variable",
    "VSA" to "By visual reference to the ground",
    "VSP" to "Vertical speed",
    "VTOL" to "Vertical take-off and landing",
    "VV" to "Vertical visibility",
    "W" to "West/White",
    "WAAS" to "Wide area augmentation system",
    "WAC" to "World Aeronautical Chart",
    "WAFC" to "World area forecast centre",
    "WB" to "Westbound",
    "WBAR" to "Wing bar lights",
    "WDI" to "Wind direction indicator",
    "WDSPR" to "Widespread",
    "WED" to "Wednesday",
    "WEF" to "With effect from",
    "WGS-84" to "World geodetic system - 1984",
    "WI" to "Within",
    "WID" to "Width",
    "WIE" to "With immediate effect",
    "WILCO" to "Will comply",
    "WIND" to "Wind",
    "WINTEM" to "Forecast upper wind and temperature for aviation",
    "WIP" to "Work in progress",
    "WKN" to "Weakening",
    "WNW" to "West-north-east",
    "WO" to "Without",
    "WPT" to "Way-point",
    "WRNG" to "Warning",
    "WS" to "Wind shear",
    "WSPD" to "Wind speed",
    "WSW" to "West-south-west",
    "WT" to "Weight",
    "WTSPT" to "Waterspout",
    "WX" to "Weather",
    "X" to "Cross",
    "XBAR" to "Crossbar of approach lighting system",
    "XS" to "Atmospherics",
    "Y" to "Yellow",
    "YCZ" to "Yellow Caution zone",
    "YES" to "Yes",
    "YR" to "Your",
    "Z" to "Coordinated Universal Time"
)